In [40]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 33 ms
Wall time: 965 ms


In [41]:
data = np.random.randn(2,3)
data

array([[-0.30925394, -0.90850468,  0.21465571],
       [-0.332995  , -0.2397633 ,  0.04586544]])

In [42]:
data*10

array([[-3.09253944, -9.08504681,  2.14655715],
       [-3.32994999, -2.39763302,  0.45865442]])

In [43]:
data+data

array([[-0.61850789, -1.81700936,  0.42931143],
       [-0.66599   , -0.4795266 ,  0.09173088]])

In [44]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [45]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [46]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [48]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [49]:
print(np.zeros(10))
print(np.ones(10))
print(np.zeros((3,6)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[3.34932697e-312 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.42800597e+248 4.11985320e-033]]

 [[1.48744643e-076 3.44036347e+175]
  [3.92069734e+179 7.79861180e-043]
  [3.70003421e-033 5.34852169e-038]]]


In [50]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [51]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [52]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [53]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [54]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype = np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [55]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype = np.float64)
print(int_array.astype(calibers.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [56]:
empty_uint32 = np.empty(8,dtype='u4')
print(empty_uint32)

[         0 1075314688          0 1075707904          0 1075838976
          0 1072693248]


In [57]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr*arr)
print(arr-arr)
print(1/arr)
print(arr**0.5)#指数运算

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [58]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
print(arr2)
print(arr2>arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


In [59]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8]=12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [60]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1]=12345
print(arr)
arr_slice[:]=64
print(arr)

[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]
[ 0  1  2  3  4 64 64 64  8  9]


In [61]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])

[7 8 9]


In [62]:
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [63]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d[0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]


In [64]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [65]:
print(arr3d[1,0])

[7 8 9]


In [66]:
x=arr3d[1]
print(x)
print(x[0])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


In [67]:
print(arr)
print(arr[1:6])

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64]


In [68]:
print(arr2d)
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [69]:
print(arr2d[:2,1:])

[[2 3]
 [5 6]]


In [70]:
print(arr2d[1,:2])
print(arr2d[:2,2])

[4 5]
[3 6]


In [71]:
print(arr2d[:,:1])
arr2d[:2,1:]=0
print(arr2d)

[[1]
 [4]
 [7]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


In [72]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Jow'])
data = np.random.randn(7,4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Jow']
[[ 1.60780892 -0.11299474 -0.40812561  0.50083757]
 [-0.44132449  0.04992976  0.07681561  0.20484172]
 [-1.44000865 -0.50927105 -0.97866901 -0.91274071]
 [-0.46905537 -0.02183622  2.17365989  0.75396818]
 [ 1.76216132  0.62379004 -1.51176269  0.40537574]
 [-0.31596168 -1.6741586  -0.49672214  0.4054097 ]
 [-1.1923874  -1.28471907 -1.12710749  1.87761509]]


In [73]:
print(names == 'Bob')
print(data[names == 'Bob'])

[ True False False  True False False False]
[[ 1.60780892 -0.11299474 -0.40812561  0.50083757]
 [-0.46905537 -0.02183622  2.17365989  0.75396818]]


In [74]:
print(data[names == 'Bob',2:])
print(data[names == 'Bob',3])

[[-0.40812561  0.50083757]
 [ 2.17365989  0.75396818]]
[0.50083757 0.75396818]


In [75]:
print(names!='Bob')
print(data[~(names=='Bob')])

[False  True  True False  True  True  True]
[[-0.44132449  0.04992976  0.07681561  0.20484172]
 [-1.44000865 -0.50927105 -0.97866901 -0.91274071]
 [ 1.76216132  0.62379004 -1.51176269  0.40537574]
 [-0.31596168 -1.6741586  -0.49672214  0.4054097 ]
 [-1.1923874  -1.28471907 -1.12710749  1.87761509]]


In [76]:
cond = names =='Bob'
print(data[~cond])

[[-0.44132449  0.04992976  0.07681561  0.20484172]
 [-1.44000865 -0.50927105 -0.97866901 -0.91274071]
 [ 1.76216132  0.62379004 -1.51176269  0.40537574]
 [-0.31596168 -1.6741586  -0.49672214  0.4054097 ]
 [-1.1923874  -1.28471907 -1.12710749  1.87761509]]


In [77]:
mask = (names == 'Bob')|(names == 'Will')
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[ 1.60780892 -0.11299474 -0.40812561  0.50083757]
 [-1.44000865 -0.50927105 -0.97866901 -0.91274071]
 [-0.46905537 -0.02183622  2.17365989  0.75396818]
 [ 1.76216132  0.62379004 -1.51176269  0.40537574]]


In [79]:
data[data<0]=0
print(data)

[[1.60780892 0.         0.         0.50083757]
 [0.         0.04992976 0.07681561 0.20484172]
 [0.         0.         0.         0.        ]
 [0.         0.         2.17365989 0.75396818]
 [1.76216132 0.62379004 0.         0.40537574]
 [0.         0.         0.         0.4054097 ]
 [0.         0.         0.         1.87761509]]


In [80]:
data[names!='Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.         0.04992976 0.07681561 0.20484172]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.         0.         0.4054097 ]
 [7.         7.         7.         7.        ]]


In [81]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [82]:
print(arr[[4,3,0,6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [83]:
print(arr[[-3,-5,-7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [84]:
arr = np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2],[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [87]:
print(arr[[1,5,7,2]][:,[0,3,2,1]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [88]:
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [89]:
arr = np.random.randn(6,3)
print(arr)
print(np.dot(arr.T,arr))

[[-1.05546974 -0.20703168 -0.08603549]
 [ 0.63058632  0.89825762 -0.57325169]
 [-0.08269119 -1.05031106 -1.1860545 ]
 [ 0.83097841  1.41477348 -1.31909357]
 [ 0.42063147 -0.46550792 -0.51441277]
 [ 0.77478037  0.79208289  1.1340067 ]]
[[ 2.98623388  2.46532532 -0.60651091]
 [ 2.46532532  4.79855912  0.02008244]
 [-0.60651091  0.02008244  5.03334444]]
