In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 34 ms
Wall time: 1.22 s


In [2]:
data = np.random.randn(2,3)
data

array([[-0.26543458, -1.26747992, -0.06842347],
       [ 0.58826398,  0.87569217,  0.87221915]])

In [3]:
data*10

array([[ -2.65434576, -12.67479922,  -0.68423472],
       [  5.88263984,   8.75692165,   8.72219146]])

In [4]:
data+data

array([[-0.53086915, -2.53495984, -0.13684694],
       [ 1.17652797,  1.75138433,  1.74443829]])

In [5]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [6]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [7]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [9]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [10]:
print(np.zeros(10))
print(np.ones(10))
print(np.zeros((3,6)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[2.41471496e-312 2.81617418e-322]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 5.74084271e+169]]

 [[7.78717372e-091 6.49265610e+169]
  [3.63372836e+174 1.50262981e-076]
  [6.48224659e+170 4.93432906e+257]]]


In [11]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [13]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [14]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [15]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype = np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [16]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype = np.float64)
print(int_array.astype(calibers.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [17]:
empty_uint32 = np.empty(8,dtype='u4')
print(empty_uint32)

[         0 1075314688          0 1075707904          0 1075838976
          0 1072693248]


In [18]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr*arr)
print(arr-arr)
print(1/arr)
print(arr**0.5)#指数运算

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [19]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
print(arr2)
print(arr2>arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


In [20]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8]=12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [21]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1]=12345
print(arr)
arr_slice[:]=64
print(arr)

[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]
[ 0  1  2  3  4 64 64 64  8  9]


In [22]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])

[7 8 9]


In [23]:
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [24]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d[0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]


In [25]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [26]:
print(arr3d[1,0])

[7 8 9]


In [27]:
x=arr3d[1]
print(x)
print(x[0])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


In [28]:
print(arr)
print(arr[1:6])

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64]


In [29]:
print(arr2d)
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [30]:
print(arr2d[:2,1:])

[[2 3]
 [5 6]]


In [31]:
print(arr2d[1,:2])
print(arr2d[:2,2])

[4 5]
[3 6]


In [32]:
print(arr2d[:,:1])
arr2d[:2,1:]=0
print(arr2d)

[[1]
 [4]
 [7]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


In [33]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Jow'])
data = np.random.randn(7,4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Jow']
[[-0.30970366 -0.18238369  1.28087802 -2.78515217]
 [ 0.33830778  0.07014306  0.56366877 -0.14692022]
 [ 0.01317589  0.59028265 -1.05111823 -1.42698904]
 [-0.40364402  0.03852072  0.21385407  0.03206413]
 [ 0.28559463 -1.62925339  0.67799056 -1.20161798]
 [-0.44258133  0.97908561 -0.39419602 -0.91071117]
 [-0.69688192 -0.08732349 -1.43109253  0.18786795]]


In [35]:
print(names == 'Bob')
print(data[names == 'Bob'])

[ True False False  True False False False]
[[-0.30970366 -0.18238369  1.28087802 -2.78515217]
 [-0.40364402  0.03852072  0.21385407  0.03206413]]


In [36]:
print(data[names == 'Bob',2:])
print(data[names == 'Bob',3])

[[ 1.28087802 -2.78515217]
 [ 0.21385407  0.03206413]]
[-2.78515217  0.03206413]


In [37]:
print(names!='Bob')
print(data[~(names=='Bob')])

[False  True  True False  True  True  True]
[[ 0.33830778  0.07014306  0.56366877 -0.14692022]
 [ 0.01317589  0.59028265 -1.05111823 -1.42698904]
 [ 0.28559463 -1.62925339  0.67799056 -1.20161798]
 [-0.44258133  0.97908561 -0.39419602 -0.91071117]
 [-0.69688192 -0.08732349 -1.43109253  0.18786795]]


In [38]:
cond = names =='Bob'
print(data[~cond])

[[ 0.33830778  0.07014306  0.56366877 -0.14692022]
 [ 0.01317589  0.59028265 -1.05111823 -1.42698904]
 [ 0.28559463 -1.62925339  0.67799056 -1.20161798]
 [-0.44258133  0.97908561 -0.39419602 -0.91071117]
 [-0.69688192 -0.08732349 -1.43109253  0.18786795]]
