In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 29 ms
Wall time: 1 s


In [2]:
data = np.random.randn(2,3)
data

array([[ 0.71621908,  0.45176862,  0.04891237],
       [-0.10517022,  0.15929405, -0.22135638]])

In [3]:
data*10

array([[ 7.16219079,  4.51768623,  0.48912371],
       [-1.0517022 ,  1.59294052, -2.21356379]])

In [4]:
data+data

array([[ 1.43243816,  0.90353725,  0.09782474],
       [-0.21034044,  0.3185881 , -0.44271276]])

In [5]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [6]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [7]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [9]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [11]:
print(np.zeros(10))
print(np.ones(10))
print(np.zeros((3,6)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 4.00544531e-307]
  [6.89809225e-307 1.02360867e-306]
  [9.79107872e-307 1.60218491e-306]]

 [[1.33508845e-306 1.33511969e-306]
  [6.23037996e-307 6.23053954e-307]
  [7.56603882e-307 1.42410974e-306]]]


In [12]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [13]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [14]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [15]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [16]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype = np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [17]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype = np.float64)
print(int_array.astype(calibers.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [18]:
empty_uint32 = np.empty(8,dtype='u4')
print(empty_uint32)

[1 2 3 4 5 6 7 8]
